version: '3'
services:
  domesticapp-db:
    image: postgres:13
    env_file:
      - ./data/.env
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./data/records.sql:/docker-entrypoint-initdb.d/records.sql
      - ./data/triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
      - ./data/functions.sql:/docker-entrypoint-initdb.d/functions.sql
      - ./data/procedures.sql:/docker-entrypoint-initdb.d/procedures.sql
      - ./data/views.sql:/docker-entrypoint-initdb.d/views.sql
      - ./data/encryption.sql:/docker-entrypoint-initdb.d/encryption.sql
    networks:
      - domesticappnet
  domesticapp-pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmindomesticapp
    environment:
      PGADMIN_DEFAULT_EMAIL: prueba@domesticapp.com
      PGADMIN_DEFAULT_PASSWORD: abc123
    ports:
      - "5050:80"
    networks:
      - domesticappnet
  domesticapp-backend:
    build: 
      context: ./Backend/domesticapp
      dockerfile: Dockerfile
    env_file:
      - ./Backend/domesticapp/.env
    container_name: backend
    restart: always
    ports:
      - 5000:5000
    networks:
      - domesticappnet
  domesticapp-frontend:
    build: 
      context: ./Frontend/domesticapp/
      dockerfile: Dockerfile
    env_file:
      - ./Frontend/domesticapp/.env
    container_name: frontend
    restart: always
    ports:
      - 80:80
    networks:
      - domesticappnet

networks:
  domesticappnet:
    driver: bridge